services:
  postgres:
    image: postgres
    container_name: todo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    volumes:
      - postgres:/data/postgres
volumes:
  postgres: