services:
  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
  minio:
    container_name: todo-minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY_FILE: access_key
      MINIO_SECRET_KEY_FILE: secret_key
    volumes:
      - minio_storage:/data
    command: server --console-address ":9001" /data
volumes:
  mongo:
  minio_storage: